# Generated by Django 2.2.7 on 2021-07-06 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0004_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
