# Generated by Django 3.2.4 on 2021-07-08 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0009_news'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='New',
        ),
    ]
