# Generated by Django 3.2.4 on 2021-07-08 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0010_rename_news_new'),
    ]

    operations = [
        migrations.DeleteModel(
            name='New',
        ),
    ]
