# Generated by Django 3.2.4 on 2021-07-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0011_delete_new'),
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('heading_uz', models.CharField(max_length=500)),
                ('heading_ru', models.CharField(max_length=500)),
                ('text_uz', models.TextField()),
                ('text_ru', models.TextField()),
            ],
        ),
    ]
