# Generated by Django 3.2.4 on 2021-07-08 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0012_new'),
    ]

    operations = [
        migrations.DeleteModel(
            name='New',
        ),
    ]
